(** Modules we use to interact with the host (to which we are a client). *)

include Wayland.Wayland_client
include Wayland_protocols.Xdg_shell_client
include Wayland_protocols.Xdg_output_unstable_v1_client
include Wayland_protocols.Gtk_primary_selection_client
include Wayland_protocols.Wp_primary_selection_unstable_v1_client
include Wayland_protocols.Server_decoration_client
include Wayland_protocols.Xdg_decoration_unstable_v1_client
include Wayland_protocols.Relative_pointer_unstable_v1_client
include Wayland_protocols.Pointer_constraints_unstable_v1_client
include Wayland_protocols.Viewporter_client
include Wayland_protocols.Cursor_shape_v1_client
